# -*- coding: utf-8 -*-
"""Week4_Student_Performance_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPa2S1Fn4iOZ9x3Al_58UfN2mT3HSPQQ
"""

!pip install faker

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from faker import Faker
fake = Faker()

np.random.seed(0)

data = {
    "Student_ID": np.random.choice(np.arange(1000, 9999), size=250, replace=False),
    "Name": [fake.name() for i in range(250)],
    "Gender": np.random.choice(["Male", "Female"], size=250),
    "Department": np.random.choice(["CSE", "IT", "ECE"], size=250),
    "Year": np.random.choice([1, 2, 3], size=250),
    "Math_Marks": np.random.randint(0, 101, size=250),
    "Science_Marks": np.random.randint(0, 101, size=250),
    "English_Marks": np.random.randint(0, 101, size=250),
    "Attendance": np.random.randint(50, 101, size=250),
    "Internals_Marks": np.random.randint(0, 26, size=250)
}

data = pd.DataFrame(data)
data

print("Means:\n")
print(df[['Math_Marks', 'Science_Marks', 'English_Marks']].mean())

print("Medians:\n")
print(df[['Math_Marks', 'Science_Marks', 'English_Marks']].median())

print("Modes:\n")
print(df[['Math_Marks', 'Science_Marks', 'English_Marks']].mode().iloc[0])

print("Standard Deviation:\n")
print(df[['Math_Marks', 'Science_Marks', 'English_Marks']].std())

data["Total_Marks"] = data["Math_Marks"] + data["Science_Marks"] + data["English_Marks"]

data["Average"] = data["Total_Marks"] / 3

data

def grade(avg):
    if avg >= 90:
        return "A"
    elif avg >= 75:
        return "B"
    elif avg >= 60:
        return "C"
    elif avg >= 50:
        return "D"
    else:
        return "Fail"

data["Grade"] = data["Average"].apply(grade)

data

top_students = data.sort_values(by="Total_Marks", ascending=False).head(10)

print("Top 10 Students")
print(top_students[["Name","Department","Total_Marks","Grade"]])

low_students = data[data["Grade"] == "Fail"]

print("Low Performing Students")
print(low_students[["Name","Department","Total_Marks","Grade"]])

department_wise = data.groupby("Department")["Average"].mean()

print(department_wise)

department_wise.plot(kind="bar")
plt.title("Department-wise Performance")
plt.show()

year_wise = data.groupby("Year")["Average"].mean()

print(year_wise)

year_wise.plot(kind="bar")
plt.title("Year-wise Performance")
plt.show()

gender_perf = data.groupby("Gender")["Average"].mean()

print(gender_perf)

gender_perf.plot(kind="bar")
plt.title("Gender-wise Performance")
plt.show()

plt.scatter(data["Attendance"], data["Average"])
plt.title("Attendance vs Marks")
plt.xlabel("Attendance")
plt.ylabel("Marks")
plt.show()

plt.scatter(data["Internals_Marks"], data["Average"])
plt.title("Internals vs Average")
plt.xlabel("Internals Marks")
plt.ylabel("Average")
plt.show()

grade_count = data["Grade"].value_counts()

plt.pie(grade_count, labels=grade_count.index, autopct="%1.1f%%")
plt.title("Grade Distribution")
plt.show()

plt.hist(data["Average"], bins=10)
plt.title("Average Marks Distribution")
plt.xlabel("Average Marks")
plt.ylabel("Number of Students")
plt.show()

data.to_csv("student_performance.csv", index=False)

print("Dataset saved successfully")